### ISSUE TITLE
mAP evaluation

### ISSUE THREAD

**Issue by xiaodanhu** [MCG-NJU/RTD-Action#11]
Hi, thanks for your interesting work! I'm wondering when would you share the evaluation code for calculating the Mean Average Precision (mAP)? Thanks so much!

**Comment by JackyTown** [comment]
https://github.com/frostinassiky/gtad/blob/master/evaluation/eval_detection.py

**Comment by xiaodanhu** [comment]
Thank so much for your quick response!

**Comment by klauscc** [comment]
Hi, could you also share the scripts that feed in your eval results to the `eval_detection.py` and produce the mAP values?
The eval results are binary classification and need additional classifiers. Could you also share the scores of the classifiers?

Thanks a lot!
