### ISSUE TITLE
RTD code for ActivityNet-1.3

### ISSUE THREAD

**Issue by menghuaa** [MCG-NJU/RTD-Action#12]
Can the code of RTD-Action for ActivityNet-1.3 be rewritten from RTD-Action for THUMOS14？

**Comment by JackyTown** [comment]
Certainly.

**Comment by AwalkZY** [comment]
Will the code and data of ActivityNet-1.3 be shared in the repo? Thanks.

**Comment by kimsimple** [comment]
> Certainly.

Thank you for your wonderful work. Could you please provide the features and TEM scores of Anet ? ~

**Comment by JackyTown** [comment]
Please refer to branch 'ANet'.
