### ISSUE TITLE
TEM_scores

### ISSUE THREAD

**Issue by DoublePan-Oh** [MCG-NJU/RTD-Action#17]
What's the meaning of the _action_ _start end_ in the TEM_scores files?

Thank you for your reply.

**Comment by sparkstj** [comment]
Hi, these are the actionness, starting, and ending probabilities in the corresponding frame.

**Comment by DoublePan-Oh** [comment]
I have some questions about feature extraction.
in the paper, the frame stride is set to 8 for I3D&nbsp;, which means you divided each video into non-overlapping snippets
with consecutive 8 frames, and 8 frames is a chuck? For example, if a video has N frames, after the I3D model, the final feature dimension is (N//8, C) ?



Looking forward to your reply!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MCG-NJU/RTD-Action"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月2日(星期三) 下午2:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MCG-NJU/RTD-Action] TEM_scores (Issue #17)





 
Hi, these are the actionness, starting, and ending probabilities in the corresponding frame.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sparkstj** [comment]
Yes, but the final feature dimension is co-determined by the final avg3dpooling layer in I3D. The pooling kernel we used is (8,7,7) and the stride is (1,1,1), therefore the feature dimension should be (N//8-7, C).

**Comment by Rishitha1234** [comment]
How to implement this code??
Can you explain me in detail (step by step)??

**Comment by sparkstj** [comment]
You can check [this repo](https://github.com/hassony2/kinetics_i3d_pytorch) for detailed code. It is the exact code we use to generate thumos features, with a mild modification on the avgpooling layer after Mixed_5c (kernel from (2,7,7) to (8,7,7)) .
