### ISSUE TITLE
about activitynet feature

### ISSUE THREAD

**Issue by menghuaa** [MCG-NJU/RTD-Action#19]
Can you provide the feature of activitynet 1.3 that are rescaled to 100 via linear interpolation?The link that you provide can't visit and the other link is hard to download.

**Comment by menghuaa** [comment]
Or can you provide some features without linear interpolation？

**Comment by JackyTown** [comment]
https://github.com/PeisenZhao/Bottom-Up-TAL-with-MR/issues/5

And you can re-scale the feature with 
https://github.com/JJBOY/BMN-Boundary-Matching-Network/blob/master/data/activitynet_feature_cuhk/data_process.py

**Comment by menghuaa** [comment]
> [PeisenZhao/Bottom-Up-TAL-with-MR#5](https://github.com/PeisenZhao/Bottom-Up-TAL-with-MR/issues/5)
> 
> [您可以使用https://github.com/JJBOY/BMN-Boundary-Matching-Network/blob/master/data/activitynet_feature_cuhk/data_process.py](https://github.com/JJBOY/BMN-Boundary-Matching-Network/blob/master/data/activitynet_feature_cuhk/data_process.py)重新缩放功能 [](https://github.com/JJBOY/BMN-Boundary-Matching-Network/blob/master/data/activitynet_feature_cuhk/data_process.py)

emmm,the student of sjtu can visit the link and download the feature

**Comment by JackyTown** [comment]
![image](https://user-images.githubusercontent.com/34415909/163344814-d305c38d-503c-4fb8-a78a-e27ea572f7f7.png)
