### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by menghuaa** [MCG-NJU/RTD-Action#21]
作者您好，anet代码在我的gpu上训练时间太久，整个流程大概需要5天，这对我来说试错成本太高了。
想问下您，activitynet1.2是activitynet1.3的子类，如果我用RTD在activitynet1.2上训练，从activitynet1.3的视频特征中提取出属于activitynet1.2的视频的特征，这样是否是可以的呢？因为目前tsn的特征，只有activitynet1.3的，没有activitynet1.2的。然后我也将activitynet1.2与activitynet1.3的注释文件进行了对比，结果显示activitynet1.2的视频在activitynet1.3都存在，且视频持续时间都是一样的，每个视频annotations的数量都是一致的，仅有三个视频activitynet1.3的annotations的数量增加了一个。

**Comment by JackyTown** [comment]
I think ActivityNet-1.2 is a subset of ActivityNet-1.3, thus it is okay.

**Comment by menghuaa** [comment]
> I think ActivityNet-1.2 is a subset of ActivityNet-1.3, thus it is okay.

但是我刚才发现，activitynet1.3的tsn特征是在activitynet1.3数据集上微调过提取的，这样再从中挑选属于activitynet1.2的特征是不是有点欠妥？
其次，你有没有试过将输入到bsn tem模块中的tsn特征换成i3d特征呢？或者你是否看到过有人提供activitynet1.2的tsn特征呢？

**Comment by JackyTown** [comment]
ActivityNet-v1.2 has not been mentioned for a long time.
