### ISSUE TITLE
about thumos14 annotation

### ISSUE THREAD

**Issue by menghuaa** [MCG-NJU/RTD-Action#22]
你好，我看到您提供的thumos14_anno__action.json以及thumos14_anno_action_class_idx.json文件中video_test_0001459的duration_second、fps与您提供的thumos14_test_groundtruth.csv中的不一致，通过与gtad对比thumos14_test_groundtruth.csv中的应该是正确的。请问这是您没有注意的一个错误吗？我目前只看了这一个视频，因为我发现thumos14中有些视频的帧频并不是30fps，而在thumos14_anno__action.json、thumos14_anno_action_class_idx.json中您把所有的视频的帧频都设置成了30fps

**Comment by menghuaa** [comment]
请问您提供的thumos14数据集的特征有没有在thumos14数据集上利用thumos14数据集的监督信息进行过微调呢？

**Comment by sparkstj** [comment]
> 你好，我看到您提供的thumos14_anno__action.json以及thumos14_anno_action_class_idx.json文件中video_test_0001459的duration_second、fps与您提供的thumos14_test_groundtruth.csv中的不一致，通过与gtad对比thumos14_test_groundtruth.csv中的应该是正确的。请问这是您没有注意的一个错误吗？我目前只看了这一个视频，因为我发现thumos14中有些视频的帧频并不是30fps，而在thumos14_anno__action.json、thumos14_anno_action_class_idx.json中您把所有的视频的帧频都设置成了30fps

啊这个确实是一个bug，统一用30fps是有问题的。你可以试试对齐一下json文件和csv文件的标注，也许结果会好一点～

**Comment by sparkstj** [comment]
> 请问您提供的thumos14数据集的特征有没有在thumos14数据集上利用thumos14数据集的监督信息进行过微调呢？

没有哈
