### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by DoublePan-Oh** [MCG-NJU/RTD-Action#23]
I follow the steps of github to train and test, but the results I get is different from the paper result，I wonder if there is something I haven't noticed?
![image](https://user-images.githubusercontent.com/30366011/167561166-0a667038-632a-4caa-995d-37e9e5643f26.png)
Looking forward your reply!

**Comment by zzcxxxfzy** [comment]
Hello, may I ask, in the paper, the training is carried out in two stages, but in the code at that time, the training is carried out in three stages, why? How do they correspond to each other

**Comment by zzcxxxfzy** [comment]
Could you leave a contact information？ I want to ask you some questions

**Comment by JackyTown** [comment]
Query-based methods are less stable than anchor-based methods, and THUMOS14 is a tiny dataset.
So we think a 0.5% gap is acceptable.
You can re-run the experiment several times and may get a better result.
