### ISSUE TITLE
Hello, may I ask, in the paper, the training is carried out in two stages, but in the code at that time, the training is carried out in three stages, why? How do they correspond to each other

### ISSUE THREAD

**Issue by zzcxxxfzy** [MCG-NJU/RTD-Action#24]

**Comment by JackyTown** [comment]
The first stage includes step1 and step2 'relaxation'.
The second stage is step3 'IoU-guided re-ranking'.

**Comment by zzcxxxfzy** [comment]
> The first stage includes step1 and step2 'relaxation'. The second stage is step3 'IoU-guided re-ranking'.

Thank you very much!
