### ISSUE TITLE
ActivityNet

### ISSUE THREAD

**Issue by DoublePan-Oh** [MCG-NJU/RTD-Action#25]
Can you provide the code of ActivityNet dataset?

**Comment by JackyTown** [comment]
ANet branch.

**Comment by DoublePan-Oh** [comment]
What's the meaning of "ANet branch"?

**Comment by JackyTown** [comment]
THUMOS14: main branch
ActivityNet-1.3: ANet branch

**Comment by DoublePan-Oh** [comment]
I‘m sorry, I found the ActivityNet feature cannot be downloaded, It shows as below. Do you have any other way?
![image](https://user-images.githubusercontent.com/30366011/169187888-1be578d3-78d2-49a4-97ba-e30705aeb4f8.png)

**Comment by JackyTown** [comment]
https://github.com/PeisenZhao/Bottom-Up-TAL-with-MR/issues/5.

**Comment by DoublePan-Oh** [comment]
I want to make sure, are you using this?
![image](https://user-images.githubusercontent.com/30366011/169199084-f73c02e9-dcad-4334-92d3-896dbde85923.png)

**Comment by DoublePan-Oh** [comment]
I am sorry to bother you again,  which one do you use?
![image](https://user-images.githubusercontent.com/30366011/170160160-5716dcd8-7cc8-41ec-9f0e-1f5dc3095e3e.png)

**Comment by DoublePan-Oh** [comment]
I use the _feature of anet_i3d_feature_25fps/flow(rgb)-resize-step16_ and test with _your checkpoint_best_auc.pth_, but the resuts I get is this. 
![image](https://user-images.githubusercontent.com/30366011/170167991-e1a168e2-6812-478b-8b6a-14b6e787c404.png)

**Comment by DoublePan-Oh** [comment]
When I retrain the Anet, it will have this problem after some epochs, maily in the case of evaluation. I don't know why have this problem.  Looking forward your reply!
![image](https://user-images.githubusercontent.com/30366011/170195323-7304638e-d56a-4639-a75c-b2f07b6ab87b.png)
