### ISSUE TITLE
ANet

### ISSUE THREAD

**Issue by DoublePan-Oh** [MCG-NJU/RTD-Action#26]
I want to know, which one the feature file do you use?
![image](https://user-images.githubusercontent.com/30366011/170606802-27eda43e-42e5-455c-b19c-2b8d8d6dd315.png)

And I use the feature of _anet_i3d_feature_25fps/flow(rgb)-resize-step16_ and test with your checkpoint_best_auc.pth, but the resuts I get is this.
![image](https://user-images.githubusercontent.com/30366011/170606885-05add942-1e00-4aad-b03b-6a3748fa5214.png)

**Comment by DoublePan-Oh** [comment]
And I try to retrain the model,  but the results can not reach the result of your paper, where is the problem?

**Comment by JackyTown** [comment]
How do you RE-SCALE the feature to 100?

I reproduced the results on more than 2 machines and made the screenshot of the performance available.

**Comment by JackyTown** [comment]
When I used the feature, there were not so many choices.

There were only initial I3D features, and I had to re-scale them.

**Comment by DoublePan-Oh** [comment]
I use this function to re-scale to 100.
![image](https://user-images.githubusercontent.com/30366011/170616771-9da31977-4ac7-47a0-9c77-4eae150374b0.png)

Is this correct?

**Comment by DoublePan-Oh** [comment]
Is it related to batch size? I can't set 128 batch size on one gpu, I can only set 32 or 64 batch

**Comment by JackyTown** [comment]
Maybe you can try 128 batch size with DP,
but I do not think batch size will affect the evaluation performance.

**Comment by DoublePan-Oh** [comment]
I find in your code, the _temporal_scale_ is not used?
![image](https://user-images.githubusercontent.com/30366011/170643366-f4fb8ebe-8806-45e5-ab27-7be1e0f68c5b.png)

**Comment by JackyTown** [comment]
https://github.com/MCG-NJU/RTD-Action/blob/ANet/datasets/anet.py#L68-L71

**Comment by JackyTown** [comment]
I will upload my re-scaled features.

**Comment by DoublePan-Oh** [comment]
Thanks for your reply !
