### ISSUE TITLE
about RTD in Anet

### ISSUE THREAD

**Issue by menghuaa** [MCG-NJU/RTD-Action#28]
Hello, I see that your paper combines the proposals generated by RTD on activitynet1.3 with untrimmednet to get the detection result. Can you provide the video classification results or model of untrimmednet training on activitynet1.3?

**Comment by JackyTown** [comment]
https://github.com/frostinassiky/gtad/blob/3f145d5d3a8ce7ac8d2b985934dbb575ca1b7981/gtad_postprocess.py#L129
