### ISSUE TITLE
How can I get a multi-scale proposal

### ISSUE THREAD

**Issue by ZhongkaiZ** [MCG-NJU/RTD-Action#8]
Ask a question again. 
Through experiments, the model makes proposals in different positions by sliding the window. The length of the proposal is **basically the same**. This phenomenon is due to the setting of positional embedding or other reasons. I added the start and end score convolution to the overall model to train together. @tony2016uestc

**Comment by JackyTown** [comment]
'The length of the proposal is basically the same.' 
I've never been in this situation before, and I think it has nothing to do with positional embedding.

**Comment by ZhongkaiZ** [comment]
id | f-init | f-end | score | video-name |  duration
-- | -- | -- | -- | -- | --
59272 | 8941.171587 | 8977.378497 | 0.617192626 | youtu_fps_5 | 36.2069108
31496 | 261.2841475 | 297.6285645 | 0.605475843 | youtu_fps_5 | 36.344417
59144 | 8901.180378 | 8937.332202 | 0.603523493 | youtu_fps_5 | 36.151824
57480 | 8381.318635 | 8417.45 | 0.59566766 | youtu_fps_5 | 36.1313652
31880 | 381.2441874 | 417.521347 | 0.592478871 | youtu_fps_5 | 36.27715969
57736 | 8461.184256 | 8497.324283 | 0.592164576 | youtu_fps_5 | 36.14002676
59240 | 8931.141665 | 8967.450015 | 0.590808988 | youtu_fps_5 | 36.30835028
57448 | 8371.069671 | 8407.376627 | 0.582358301 | youtu_fps_5 | 36.30695572
5672 | 8932.751745 | 9112.894943 | 0.581983328 | youtu_fps_1 | 180.143198
5320 | 8305.016166 | 8486.745621 | 0.580924988 | youtu_fps_1 | 181.729455
31752 | 341.2028193 | 377.4039001 | 0.580215931 | youtu_fps_5 | 36.2010808
59112 | 8891.13182 | 8927.524298 | 0.57909888 | youtu_fps_5 | 36.39247856
51720 | 6581.16676 | 6617.600854 | 0.578297973 | youtu_fps_5 | 36.43409481
58280 | 8631.045631 | 8667.365689 | 0.577133536 | youtu_fps_5 | 36.32005787

**Comment by JackyTown** [comment]
Please check the log and make sure that loss is dropping.

**Comment by ZhongkaiZ** [comment]
> 'The length of the proposal is basically the same.'
> I've never been in this situation before, andI think it has nothing to do with positional embedding.

Thank you for you reply,I found that the parameters of '[pred_boxes](https://github.com/MCG-NJU/RTD-Action/blob/ae51cf06d1c138bff3a41a3d014939bd409550a8/models/rtd.py#L122)' in a batch are equally distributed.

**Comment by ZhongkaiZ** [comment]
> Please check the log and make sure that loss is dropping.
Train loss is dropping
such as :
"train_class_error": 1.6918702916952688, "train_loss": 1.4451521763076676,
"train_class_error": 1.5234429799695726, "train_loss": 1.3731449029435672
"train_class_error": 1.2739102990058675, "train_loss": 1.3295617185044655,

**Comment by JackyTown** [comment]
Maybe you can check outputs of starting and ending score conv.

**Comment by ZhongkaiZ** [comment]
> Maybe you can check outputs of starting and ending score conv.

tanks,I will try to transfer the weight of BMN and freeze the update.
