### ISSUE TITLE
One question about the the boundary attentive module

### ISSUE THREAD

**Issue by 3huo** [MCG-NJU/RTD-Action#9]
Hi~
Does the input feature and start/end scores is pretrained in advance?

**Comment by 3huo** [comment]
And I also concern that if my start and end scores are predicted very correctly, then the center feature after multiplication could go to zero. can it still very effective for proposal generation?

**Comment by JackyTown** [comment]
No, input features and start/end scores are directly trained on target datasets.

Actually, start and end scores cannot be predicted very correctly. (If boundary probability of center features are zero, TAPG will be totally solved.) For more details, you can refer to Appendices E.

**Comment by 3huo** [comment]
Oh~, Thank you for your replying! 
so... the input features training process and the encode/decode process are trained separately?

**Comment by sparkstj** [comment]
Yes
